on: pull_request

name: Check

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: yarn install

      - run: yarn test
