on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Publish

jobs:
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org
          always-auth: true

      - uses: phips28/gh-action-bump-version@8d1fb3d7cdc88a2df8252eac3db53d31958b98e7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn install

      - run: yarn build

      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
