on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Publish

jobs:
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - run: yarn install

      - run: yarn build

      - name: Publish
        run: |
          NEW_PATCH_VERSION=$(npm view --json | jq -r ".version" | awk -F'.' '{print $1"."$2"."$3+1}')
          yarn publish --access public --tag "$NEW_PATCH_VERSION"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
